export const GET_BLOGPOSTS_PENDING = 'constants/GET_BLOGPOSTS_PENDING';
export const GET_BLOGPOSTS_SUCCESS = 'constants/GET_BLOGPOSTS_SUCCESS';
export const GET_BLOGPOSTS_ERROR = 'constants/GET_BLOGPOSTS_ERROR';
export const DELETE_BLOGPOSTS_PENDING = 'constants/DELETE_BLOGPOSTS_PENDING';
export const DELETE_BLOGPOSTS_SUCCESS = 'constants/DELETE_BLOGPOSTS_SUCCESS';
export const DELETE_BLOGPOSTS_ERROR = 'constants/DELETE_BLOGPOSTS_ERROR';
